### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Maroof02** [Scientific-Guy/chatcord#2] opened 2021-04-19 16:09 UTC
The chatcord npm isnt working.

**Comment by scientific-dev** [comment] 2021-04-19 16:44
This is issue is a duplicate of [#1](https://github.com/Scientific-Guy/chatcord/issues/1)

**Closed as completed by scientific-dev** 2021-04-19 16:44 UTC
Labels: duplicate

**Comment by Maroof-0786** [comment] 2021-04-20 07:55
The NPM package isn't working :c
It was working a few days before but now it isn't. Please fix it :c

**Comment by Ashthetik** [comment] 2021-04-20 07:59
> The NPM package isn't working :c
> It was working a few days before but now it isn't. Please fix it :c

Hi there, the team is aware of this, Im working with them to fix this issue, im planning on releasing a PR of this to resolve the issue within the next 48 hours.

Thanks, Kaz

**Comment by scientific-dev** [comment] 2021-04-20 08:15
> The NPM package isn't working :c
> It was working a few days before but now it isn't. Please fix it :c

I accept but dicuss about this at [#1](https://github.com/Scientific-Guy/chatcord/issues/1) because this is a duplicate one. And the package is broken. Our members, maintainers, developers will fix this asap.
